// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using top_medkit_dblayer;

#nullable disable

namespace top_medkit_dblayer.Migrations
{
    [DbContext(typeof(DrugContext))]
    [Migration("20230802161523_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("top_medkit_models.Models.AcceptanceMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DrugInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrugInfoId");

                    b.ToTable("AcceptanceMethods");
                });

            modelBuilder.Entity("top_medkit_models.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("MedKitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MedKitId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("top_medkit_models.Models.Drug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcceptanceMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DrugInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedKitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Remainings")
                        .HasColumnType("float");

                    b.Property<DateTime>("ShelfLife")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcceptanceMethodId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DrugInfoId");

                    b.HasIndex("MedKitId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("top_medkit_models.Models.DrugInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contraindications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Dosage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DrugInfos");
                });

            modelBuilder.Entity("top_medkit_models.Models.MedKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("MedKits");
                });

            modelBuilder.Entity("top_medkit_models.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SetOfPills")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeToTake")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DrugId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("top_medkit_models.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedKitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DrugId");

                    b.HasIndex("MedKitId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("top_medkit_models.Models.AcceptanceMethod", b =>
                {
                    b.HasOne("top_medkit_models.Models.DrugInfo", null)
                        .WithMany("AcceptanceMethod")
                        .HasForeignKey("DrugInfoId");
                });

            modelBuilder.Entity("top_medkit_models.Models.Client", b =>
                {
                    b.HasOne("top_medkit_models.Models.MedKit", null)
                        .WithMany("Clients")
                        .HasForeignKey("MedKitId");
                });

            modelBuilder.Entity("top_medkit_models.Models.Drug", b =>
                {
                    b.HasOne("top_medkit_models.Models.AcceptanceMethod", "AcceptanceMethod")
                        .WithMany()
                        .HasForeignKey("AcceptanceMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("top_medkit_models.Models.Client", null)
                        .WithMany("Drug")
                        .HasForeignKey("ClientId");

                    b.HasOne("top_medkit_models.Models.DrugInfo", "DrugInfo")
                        .WithMany()
                        .HasForeignKey("DrugInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("top_medkit_models.Models.MedKit", "MedKit")
                        .WithMany("Drugs")
                        .HasForeignKey("MedKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptanceMethod");

                    b.Navigation("DrugInfo");

                    b.Navigation("MedKit");
                });

            modelBuilder.Entity("top_medkit_models.Models.Prescription", b =>
                {
                    b.HasOne("top_medkit_models.Models.Client", "Client")
                        .WithMany("Prescription")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("top_medkit_models.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("top_medkit_models.Models.Transaction", b =>
                {
                    b.HasOne("top_medkit_models.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("top_medkit_models.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("top_medkit_models.Models.MedKit", "MedKit")
                        .WithMany()
                        .HasForeignKey("MedKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Drug");

                    b.Navigation("MedKit");
                });

            modelBuilder.Entity("top_medkit_models.Models.Client", b =>
                {
                    b.Navigation("Drug");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("top_medkit_models.Models.DrugInfo", b =>
                {
                    b.Navigation("AcceptanceMethod");
                });

            modelBuilder.Entity("top_medkit_models.Models.MedKit", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Drugs");
                });
#pragma warning restore 612, 618
        }
    }
}
